# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EdgeBridgeTutorialApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EdgeBridgeTutorialApp
  pod 'AEPAnalytics'
  pod 'AEPCore'
  pod 'AEPIdentity'
  pod 'AEPServices'
=begin
  pod 'AEPAssurance'
  pod 'AEPEdge'
  pod 'AEPEdgeBridge', :git => 'https://github.com/adobe/aepsdk-edgebridge-ios.git', :tag => 'dev'
  pod 'AEPEdgeConsent'
  pod 'AEPEdgeIdentity'
  pod 'AEPLifecycle'
=end
end
